;;;; package.lisp

(defpackage :dc-utilities
  (:use :cl :cl-ppcre :trivial-utf-8 :sb-thread :sb-ext)
  (:import-from :ironclad
                :ascii-string-to-byte-array
                :byte-array-to-hex-string
                :digest-sequence
                :sha512)
  (:export

   *ds-timings*
   alist-values
   bytes-to-uint
   change-per-second
   command-line-options
   create-directory
   cull-named-params
   directory-exists
   distinct-elements
   ds
   ds-clone
   ds-from-json
   ds-get
   ds-keys
   ds-list
   ds-merge
   ds-set
   ds-to-json
   ds-type
   document-package
   elapsed-time
   factorial
   fast-compress
   fast-decompress
   fib
   file-exists
   file-extension
   file-line-count
   filter-file
   flatten
   freeze
   freeze-n-spew
   hash-keys
   hash-string
   hash-values
   home-settings-file
   home-based
   index-values
   interrupt-sleep
   interruptible-sleep
   join-paths
   k-combination
   list-keys
   list-values
   load-settings
   lof
   log-entry
   make-time-tracker
   mark-time
   memoize
   memoize-with-limit
   parse-number
   path-only
   range
   read-one-line
   read-settings-file
   replace-regexs
   replace-extension
   scrape-string
   sequence-bytes-to-uint
   sequence-uint-to-bytes
   setting
   setting
   shell-execute
   shift
   shuffle
   slurp
   slurp-binary
   slurp-n-thaw
   spew
   split-n-trim
   store-delete
   store-fetch
   store-path
   store-save
   temp-file-name
   thaw
   thread-pool-job-queue
   thread-pool-progress
   thread-pool-run-time
   thread-pool-start
   thread-pool-start-time
   thread-pool-stop
   thread-pool-stop-time
   thread-pool-time-to-go
   time-to-go
   timestamp
   to-ascii
   trim
   uint-to-bytes
   unique-name
   unique-filename
   unshift
   verify-string
   with-lines-in-file
   ))

